language: node_js
node_js:
- 7
cache:
  directories:
  - node_modules # NPM packages
  - $(npm config get prefix)/bin/gulp
  - $(npm config get prefix)/bin/firebase
  - /home/travis/.nvm/versions/node/v7.10.1/lib/node_modules
  - $HOME/.cache/pip
  - /home/travis/.local/bin
install:
- pip install grow==0.3.9 --user $USER
- npm install -g gulp
- npm install -g firebase-tools
- npm install
- npm update
script:
- 'if [ "${TRAVIS_BRANCH}" = "production" ]; then firebase use production; fi'
- 'if [ "${TRAVIS_BRANCH}" = "master" ]; then firebase use staging; fi'
- grow build
- ls build
after_success:
- firebase deploy --token "$FIREBASE_TOKEN" --non-interactive
branches:
  only:
  - production
  - master
env:
  global:
    secure: RRx3CaLmCC0rA+MOYXTI3HTAMc2TI9AQcodUfZhr+vNEL8d0q09EZkYU/TjkRx9VQ1paOT1AmxNQJtHhysIS7B/pSAZoNG9bPC5UXmiZHVLbRB4qPmMMte9zdfKanGY3/g3zt2qOTUVVL4ymDy5xK2uYZ/KgkrDx1gGH3mSoTO6gK79I4nisJYDcRfzI/UUvrNkdjlFYrFnZbnMdnqZSryuv7CrdZWpYtLDryzJ+bcgq6Vr2liiKwmVb+/tff3EblAzBcWMAM4I0MzRaM+Mahw0EEENc24brtVoQTbvSdXXJ9CEIfWjykSyZh0WrZkx3tKY95GDr9PCHEkyI5d2kUGYDbRjjrEuBEdPTcjx6zZ2vXUlVPeDxNwLO1WZwVy0Om1dg/jwPjVDtsubjBaC+4XezJCywaZruGD6Q0iStemMVapN19SbGJzo9uYG8EvVB4OFlmY2l/fOadTIC9YHpYJREhGc2DBW9jHfTK1dgyW1JpnFgieEOSw24gsvbxSSV5db7tJU36Pt1Kkcu3IZnYyHlBUmYKZ24cizh6azfkHRaLvSvdJuvx0euuoz/WOJ77toUD6wPc0/OtrKnkCfQowtciMdnKNhuu4JpegdZ9gQqpV2gQ0XpPgxc4afKCd0L5QiUNFCu1J+fQ0obclqWZpC0VzHdDpNMckv4I7XqnhI=
